// Mocks generated by Mockito 5.4.4 from annotations
// in rabble/test/auth/auth_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:rabble/core/config/export.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBehaviorSubject_0<T> extends _i1.SmartFake
    implements _i2.BehaviorSubject<T> {
  _FakeBehaviorSubject_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRabbleBaseState_1 extends _i1.SmartFake
    implements _i2.RabbleBaseState {
  _FakeRabbleBaseState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamTransformer_2<S, T> extends _i1.SmartFake
    implements _i3.StreamTransformer<S, T> {
  _FakeStreamTransformer_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthCubit extends _i1.Mock implements _i2.AuthCubit {
  MockAuthCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BehaviorSubject<int> get currentIndex => (super.noSuchMethod(
        Invocation.getter(#currentIndex),
        returnValue: _FakeBehaviorSubject_0<int>(
          this,
          Invocation.getter(#currentIndex),
        ),
      ) as _i2.BehaviorSubject<int>);

  @override
  _i2.BehaviorSubject<double> get containerWidth => (super.noSuchMethod(
        Invocation.getter(#containerWidth),
        returnValue: _FakeBehaviorSubject_0<double>(
          this,
          Invocation.getter(#containerWidth),
        ),
      ) as _i2.BehaviorSubject<double>);

  @override
  _i2.BehaviorSubject<bool> get isActiveNextButtonController =>
      (super.noSuchMethod(
        Invocation.getter(#isActiveNextButtonController),
        returnValue: _FakeBehaviorSubject_0<bool>(
          this,
          Invocation.getter(#isActiveNextButtonController),
        ),
      ) as _i2.BehaviorSubject<bool>);

  @override
  _i2.BehaviorSubject<List<double>> get progressValues$subject =>
      (super.noSuchMethod(
        Invocation.getter(#progressValues$subject),
        returnValue: _FakeBehaviorSubject_0<List<double>>(
          this,
          Invocation.getter(#progressValues$subject),
        ),
      ) as _i2.BehaviorSubject<List<double>>);

  @override
  List<int> get storyDurations => (super.noSuchMethod(
        Invocation.getter(#storyDurations),
        returnValue: <int>[],
      ) as List<int>);

  @override
  List<_i2.OnBoardModel> get data => (super.noSuchMethod(
        Invocation.getter(#data),
        returnValue: <_i2.OnBoardModel>[],
      ) as List<_i2.OnBoardModel>);

  @override
  set data(List<_i2.OnBoardModel>? _data) => super.noSuchMethod(
        Invocation.setter(
          #data,
          _data,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.BehaviorSubject<String> get selectedCountryImage$ => (super.noSuchMethod(
        Invocation.getter(#selectedCountryImage$),
        returnValue: _FakeBehaviorSubject_0<String>(
          this,
          Invocation.getter(#selectedCountryImage$),
        ),
      ) as _i2.BehaviorSubject<String>);

  @override
  set selectedCountryImage$(
          _i2.BehaviorSubject<String>? _selectedCountryImage$) =>
      super.noSuchMethod(
        Invocation.setter(
          #selectedCountryImage$,
          _selectedCountryImage$,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.BehaviorSubject<bool> get focus$ => (super.noSuchMethod(
        Invocation.getter(#focus$),
        returnValue: _FakeBehaviorSubject_0<bool>(
          this,
          Invocation.getter(#focus$),
        ),
      ) as _i2.BehaviorSubject<bool>);

  @override
  set focus$(_i2.BehaviorSubject<bool>? _focus$) => super.noSuchMethod(
        Invocation.setter(
          #focus$,
          _focus$,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.BehaviorSubject<String> get selectedCountryCode$ => (super.noSuchMethod(
        Invocation.getter(#selectedCountryCode$),
        returnValue: _FakeBehaviorSubject_0<String>(
          this,
          Invocation.getter(#selectedCountryCode$),
        ),
      ) as _i2.BehaviorSubject<String>);

  @override
  set selectedCountryCode$(
          _i2.BehaviorSubject<String>? _selectedCountryCode$) =>
      super.noSuchMethod(
        Invocation.setter(
          #selectedCountryCode$,
          _selectedCountryCode$,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.BehaviorSubject<String> get ErrorCode$ => (super.noSuchMethod(
        Invocation.getter(#ErrorCode$),
        returnValue: _FakeBehaviorSubject_0<String>(
          this,
          Invocation.getter(#ErrorCode$),
        ),
      ) as _i2.BehaviorSubject<String>);

  @override
  set ErrorCode$(_i2.BehaviorSubject<String>? _ErrorCode$) =>
      super.noSuchMethod(
        Invocation.setter(
          #ErrorCode$,
          _ErrorCode$,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.BehaviorSubject<bool> get iSCompletedNumber$ => (super.noSuchMethod(
        Invocation.getter(#iSCompletedNumber$),
        returnValue: _FakeBehaviorSubject_0<bool>(
          this,
          Invocation.getter(#iSCompletedNumber$),
        ),
      ) as _i2.BehaviorSubject<bool>);

  @override
  set iSCompletedNumber$(_i2.BehaviorSubject<bool>? _iSCompletedNumber$) =>
      super.noSuchMethod(
        Invocation.setter(
          #iSCompletedNumber$,
          _iSCompletedNumber$,
        ),
        returnValueForMissingStub: null,
      );

  @override
  dynamic Function(String) get phoneC => (super.noSuchMethod(
        Invocation.getter(#phoneC),
        returnValue: (String __p0) => null,
      ) as dynamic Function(String));

  @override
  _i3.Stream<String> get phoneStream => (super.noSuchMethod(
        Invocation.getter(#phoneStream),
        returnValue: _i3.Stream<String>.empty(),
      ) as _i3.Stream<String>);

  @override
  _i3.Stream<bool> get validFPField => (super.noSuchMethod(
        Invocation.getter(#validFPField),
        returnValue: _i3.Stream<bool>.empty(),
      ) as _i3.Stream<bool>);

  @override
  _i2.RabbleBaseState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeRabbleBaseState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.RabbleBaseState);

  @override
  _i3.Stream<_i2.RabbleBaseState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i3.Stream<_i2.RabbleBaseState>.empty(),
      ) as _i3.Stream<_i2.RabbleBaseState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  _i3.StreamTransformer<String, String> get validateUsername =>
      (super.noSuchMethod(
        Invocation.getter(#validateUsername),
        returnValue: _FakeStreamTransformer_2<String, String>(
          this,
          Invocation.getter(#validateUsername),
        ),
      ) as _i3.StreamTransformer<String, String>);

  @override
  _i3.StreamTransformer<String, String> get validateEmail =>
      (super.noSuchMethod(
        Invocation.getter(#validateEmail),
        returnValue: _FakeStreamTransformer_2<String, String>(
          this,
          Invocation.getter(#validateEmail),
        ),
      ) as _i3.StreamTransformer<String, String>);

  @override
  _i3.StreamTransformer<String, String> get validatePassword =>
      (super.noSuchMethod(
        Invocation.getter(#validatePassword),
        returnValue: _FakeStreamTransformer_2<String, String>(
          this,
          Invocation.getter(#validatePassword),
        ),
      ) as _i3.StreamTransformer<String, String>);

  @override
  _i3.StreamTransformer<String, String> get validatePhone =>
      (super.noSuchMethod(
        Invocation.getter(#validatePhone),
        returnValue: _FakeStreamTransformer_2<String, String>(
          this,
          Invocation.getter(#validatePhone),
        ),
      ) as _i3.StreamTransformer<String, String>);

  @override
  _i3.StreamTransformer<String, String> get validateOtp => (super.noSuchMethod(
        Invocation.getter(#validateOtp),
        returnValue: _FakeStreamTransformer_2<String, String>(
          this,
          Invocation.getter(#validateOtp),
        ),
      ) as _i3.StreamTransformer<String, String>);

  @override
  _i3.StreamTransformer<String, String> get validateEmpty =>
      (super.noSuchMethod(
        Invocation.getter(#validateEmpty),
        returnValue: _FakeStreamTransformer_2<String, String>(
          this,
          Invocation.getter(#validateEmpty),
        ),
      ) as _i3.StreamTransformer<String, String>);

  @override
  _i3.StreamTransformer<String, String> get validateGroupName =>
      (super.noSuchMethod(
        Invocation.getter(#validateGroupName),
        returnValue: _FakeStreamTransformer_2<String, String>(
          this,
          Invocation.getter(#validateGroupName),
        ),
      ) as _i3.StreamTransformer<String, String>);

  @override
  _i3.StreamTransformer<String, String> get validateCardNumber =>
      (super.noSuchMethod(
        Invocation.getter(#validateCardNumber),
        returnValue: _FakeStreamTransformer_2<String, String>(
          this,
          Invocation.getter(#validateCardNumber),
        ),
      ) as _i3.StreamTransformer<String, String>);

  @override
  _i3.StreamTransformer<String, String> get validateCVV => (super.noSuchMethod(
        Invocation.getter(#validateCVV),
        returnValue: _FakeStreamTransformer_2<String, String>(
          this,
          Invocation.getter(#validateCVV),
        ),
      ) as _i3.StreamTransformer<String, String>);

  @override
  _i3.StreamTransformer<String, String> get validateExpiry =>
      (super.noSuchMethod(
        Invocation.getter(#validateExpiry),
        returnValue: _FakeStreamTransformer_2<String, String>(
          this,
          Invocation.getter(#validateExpiry),
        ),
      ) as _i3.StreamTransformer<String, String>);

  @override
  _i3.Future<void> sendOtp(
    String? type, {
    String? number,
    _i2.InvitationData? invitationData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendOtp,
          [type],
          {
            #number: number,
            #invitationData: invitationData,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateUserInfo() => (super.noSuchMethod(
        Invocation.method(
          #updateUserInfo,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> verifyToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #verifyToken,
          [token],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> route() => (super.noSuchMethod(
        Invocation.method(
          #route,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void emit(_i2.RabbleBaseState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i2.Change<_i2.RabbleBaseState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
