// Mocks generated by Mockito 5.4.4 from annotations
// in rabble/test/home/home_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:rabble/core/config/export.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBehaviorSubject_0<T> extends _i1.SmartFake
    implements _i2.BehaviorSubject<T> {
  _FakeBehaviorSubject_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRabbleBaseState_1 extends _i1.SmartFake
    implements _i2.RabbleBaseState {
  _FakeRabbleBaseState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HomeCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeCubit extends _i1.Mock implements _i2.HomeCubit {
  MockHomeCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BehaviorSubject<int> get selectedIndex$ => (super.noSuchMethod(
        Invocation.getter(#selectedIndex$),
        returnValue: _FakeBehaviorSubject_0<int>(
          this,
          Invocation.getter(#selectedIndex$),
        ),
      ) as _i2.BehaviorSubject<int>);

  @override
  set selectedIndex$(_i2.BehaviorSubject<int>? _selectedIndex$) =>
      super.noSuchMethod(
        Invocation.setter(
          #selectedIndex$,
          _selectedIndex$,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.BehaviorSubject<List<_i2.NotificationData>>
      get notificationsListSubject$ => (super.noSuchMethod(
            Invocation.getter(#notificationsListSubject$),
            returnValue: _FakeBehaviorSubject_0<List<_i2.NotificationData>>(
              this,
              Invocation.getter(#notificationsListSubject$),
            ),
          ) as _i2.BehaviorSubject<List<_i2.NotificationData>>);

  @override
  set notificationsListSubject$(
          _i2.BehaviorSubject<List<_i2.NotificationData>>?
              _notificationsListSubject$) =>
      super.noSuchMethod(
        Invocation.setter(
          #notificationsListSubject$,
          _notificationsListSubject$,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.RabbleBaseState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeRabbleBaseState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.RabbleBaseState);

  @override
  _i3.Stream<_i2.RabbleBaseState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i3.Stream<_i2.RabbleBaseState>.empty(),
      ) as _i3.Stream<_i2.RabbleBaseState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<void> fetchNotifications() => (super.noSuchMethod(
        Invocation.method(
          #fetchNotifications,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void emit(_i2.RabbleBaseState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i2.Change<_i2.RabbleBaseState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
