// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyCnWwu9qdHjTln2kbzOXnYzivZkxYVsUS0',
      authDomain: "rabble-f73a4.firebase.com",
      projectId: 'rabble-f73a4',
      storageBucket: 'rabble-f73a4.appspot.com',
      messagingSenderId: '896330199240',
      appId: '1:896330199240:web:5a09c7ba48975b410cb5fd',
      measurementId: 'G-MDEMR2YFTK'  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi_Xgvj4rIajJj5k_K_kofKBFC59dAzq4',
    appId: '1:896330199240:android:ebae23f496e13d7e0cb5fd',
    messagingSenderId: '896330199240',
    projectId: 'rabble-f73a4',
    storageBucket: 'rabble-f73a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi_Xgvj4rIajJj5k_K_kofKBFC59dAzq4',
    appId: '1:896330199240:ios:551ae9537ddc1fd60cb5fd',
    messagingSenderId: '896330199240',
    projectId: 'rabble-f73a4',
    storageBucket: 'rabble-f73a4.appspot.com',
    iosClientId: '896330199240-6hoq2slnt63p3tna47fpkd0i6utesmvh.apps.googleusercontent.com',
    iosBundleId: 'com.app.rabble',
  );
}
